#!/bin/bash
case $1 in
	start)
		echo "Starting apollo web app."
		/home/argos/apollo &
		;;
	stop)
		echo "Stopping hello web app."
		sudo kill $(sudo lsof -t -i:4444)
		;;
	*)
		echo "Apollo web app service."
		echo $"Usage $0 {start|stop}"
		exit 1
esac
exit 0 
